### ISSUE TITLE
suppress output of GitHub token

### ISSUE THREAD

**Issue by DanielRuf** [Sgoettschkes/sgoettschkes.github.io#1]
You should use git push --quiet origin ... to suppress the output of the GitHub token in cleartext in the logs of Travis. You should regenerate and reencrypt it.

`https://6aa8d8faf9a5ac231506906bb868765cf4f6f122@github.com/sgoettschkes/sgoettschkes.github.io`

**Comment by Sgoettschkes** [comment]
Thank you Daniel for taking the time and making me aware of this. It's highly appreciated!

**Comment by DanielRuf** [comment]
No problem, you are welcome.
